### ISSUE TITLE
Enable use this extention for all sapi

### ISSUE THREAD

**Issue by macintoshplus** [InExtenso/win32service#11]
Remove the cli sapi restriction.

On cli SAPI full work, on other SAPI, 3 functions are disabled with an php error:

![image](https://cloud.githubusercontent.com/assets/814683/21804739/d5b813e6-d730-11e6-9f98-9b88bd5fabf1.png)

CLI SAPI PHP Infos:
```
C:\php\debug>php --ri win32service

win32service

Win32 Service support => enabled
Version => 0.1.3-dev
Current SAPI => cli

Function => State for the current SAPI
win32_start_service_ctrl_dispatcher => enabled
win32_set_service_status => enabled
win32_get_last_control_message => enabled
win32_create_service => enabled
win32_delete_service => enabled
win32_query_service_status => enabled
win32_start_service => enabled
win32_stop_service => enabled
win32_pause_service => enabled
win32_continue_service => enabled
```

**Comment by macintoshplus** [comment]
The commit [678b2830db8ca8755931897d241968199fe146ad](https://github.com/InExtenso/win32service/commit/678b2830db8ca8755931897d241968199fe146ad) implement this behavior.

**Comment by macintoshplus** [comment]
Build result is available here for test only:
* php 7.0 https://ci.appveyor.com/project/macintoshplus/win32service/build/v1.3.50/job/euuuqhm6c4i4c9k5/artifacts
* php 7.1 https://ci.appveyor.com/project/macintoshplus/win32service/build/v1.3.50/job/rmwes0euvdpy5drf/artifacts

**Comment by macintoshplus** [comment]
ping @alphp

**Comment by alphp** [comment]
Great!!!

**Comment by alphp** [comment]
Tested with PHP-7.1.1RC1: all OK.
Great job.
Best regards

**Comment by macintoshplus** [comment]
Good news !
Thanks for feedback.

**Comment by alphp** [comment]
I added a note in the manual ...
http://php.net/manual/en/win32service.installation.php

**Comment by alphp** [comment]
On Apache Lounge: https://www.apachelounge.com/viewtopic.php?t=7484

**Comment by Jan-E** [comment]
I compiled v0.1.2 yesterday into my PHP-builds:
https://www.apachelounge.com/viewtopic.php?t=6617

I will recompile with php_win32service in the phpinfo's.

**Comment by alphp** [comment]
For the CGI/FastCGI you must compile with v0.1.3.
The 0.1.2 version has a restriction to load only on CLI SAPI.

**Comment by eddokloosterman** [comment]
Some feedback after trying the new DLLs; on PHP 7.0 it does work, though running `net start <service name>` it mentions that it cannot start the service. I have a feeling this is due to the way we've setup our service script, and not due to the library, yet that is not confirmed.

**Comment by macintoshplus** [comment]
@eddokloosterman Thanks for feedback.
You can found into this repository [some example](https://github.com/InExtenso/win32service/tree/php7/examples) for tests and how to implement the service management into your script.
If you need more help for implement or understand how to this extension work, please open a new issue.

**Comment by alphp** [comment]
I have two services that use this extension and whose skeleton is the example [service.php](https://github.com/InExtenso/win32service/blob/php7/examples/service.php).
Just today I just updated the server to PHP-7.1.2_x64.
I use the binaries compiled by me, which are equivalent to the release [v1.3-dev](https://github.com/InExtenso/win32service/releases/tag/v1.3-dev) published in this repository.

**Comment by macintoshplus** [comment]
The version 1.3-dev is a wrong number version. I just added the good version [0.2.0-beta.1](https://github.com/InExtenso/win32service/releases/tag/v0.2.0-beta.1).
This version contains, one zip for PHP 7.0 with all variant (x64/x86, NTS/TS) and another zip for PHP 7.1 with all variant (x64/x86, NTS/TS).

Thanks for feedback.

I close this issue because it's solved into the version 0.2.0.

**Comment by alphp** [comment]
Two services, 10 uninterrupted days, 40000 files processed, ZERO errors.
Those are the statistics of the first 10 days of my services written with PHP-7.1.2 and the win32service extension.
These services are an important part of my company's workflow and are in production.

**Comment by macintoshplus** [comment]
Thanks for your feedback. This is a good news.

**Comment by macintoshplus** [comment]
The stable version is out : https://github.com/InExtenso/win32service/releases/tag/v0.2.0

**Comment by AnrDaemon** [comment]
Doesn't run on 7.1.4/TS/x86_64
`PHP Fatal error:  The Win32Service extension not work on PHP 7.1.0. Work with 7.1.1+ in Unknown on line 0`

Could this be a build issue? I've obtained binaries from PECL.

**Comment by alphp** [comment]
You can see PR #20 
One week ago I updated a production environment to PHP-7.1.4 / TS / x86_64 and it did not give any problems.
Binaries to test:
https://ci.appveyor.com/project/alphp/win32service/branch/php7

**Comment by AnrDaemon** [comment]
It is a building issue, PECL maintainer used PHP Version: 7.1.0 to build extension.
See http://windows.php.net/downloads/pecl/releases/win32service/0.2.0/logs/php_win32service-0.2.0-7.1-ts-vc14-x64-logs.zip

**Comment by AnrDaemon** [comment]
CI binaries worked like a charm. Thanks.

**Comment by alphp** [comment]
The [v2.0.0 release](https://github.com/InExtenso/win32service/releases/tag/v0.2.0) of this repo works correctly.
