### ISSUE TITLE
Upgrading build script to use the new php-sdk OSTC/php-sdk-binary-tools

### ISSUE THREAD

**Issue by alphp** [InExtenso/win32service#12]
The goal is to improve the build script and use the new php-sdk:
https://github.com/OSTC/php-sdk-binary-tools/tree/new_binary_tools

**Comment by alphp** [comment]
I have created a new branch for testing the build.cmd script called build.dev:
https://github.com/alphp/win32service/tree/build.dev

**Comment by alphp** [comment]
Hi,
I have updated the build script and now use the new php-sdk (#16).
The most important features are:
* YAML AppVeyor: Simplified, added new environment variables.
* Install Script (install.cmd): New, prepare the build environment
* Build Script (build.cmd): Simplified, sets the environment variables for each Architecture.
* Build Task Script (build_task.cmd): New, build the TS and NTS versions for each Architecture.
* Added new artifacts, each binary of the extensión, LICENSE file and examples are packaged as separate zip for each version (PHP release, Architecture and TS/NTS).

5 zip files are produced for each PHP release (7.0 and 7.1):
* For each variant a zip with name format "php_win32service-%APPVEYOR_REPO_TAG_NAME%-%PHP_REL%-vc14-%ZTS_SHORT%-%ARCH%.zip" is produced, similar schema as oficial pecl releases.
* For each release of PHP (7.0 and 7.1) a zip with name format "php_win32service-%APPVEYOR_REPO_TAG_NAME%-%PHP_REL%-vc14.zip" is produced, inside are all the binary variants of extensión for the PHP release.

**Comment by macintoshplus** [comment]
Thanks for this job. I closes this issue because the PR is merged.
