### ISSUE TITLE
Rename the branch php-7.0 on v1.2

### ISSUE THREAD

**Issue by macintoshplus** [InExtenso/win32service#15]
@Jan-E @alphp I want create a new branch `v1.2` from the `php-7.0` branch and close the old branch.
This would be more consistent with the reality of the sources. The `php-7.0` branch is also built for PHP-7.1.

What do you think ?

**Comment by alphp** [comment]
I think it's a good idea

**Comment by Jan-E** [comment]
In other php-extensions it is quite common practice to use 'php7' for the php7.0+ code.

It seems no good idea to name a branch after a version like v1.3 (apart from the fact that it should have been v0.1.3), unless you want old versions to be available forever (like the php 5-versions). If it has a feature you cannot merge into the php7-branch yet, name it after the feature. Something like 'php7-cgi'.

**Comment by alphp** [comment]
The scheme proposed by Jan-E is more logical, but I would rename the branch "php-7.0" as "php7-cli" and "v1.3" as "php7".

The "php-7.0" branch has a characteristic that branch "v1.3" does not have (the load restriction in CLI SAPI), so if you have to highlight the branches with specific characteristics that would be the branch "php-7.0" .

**Comment by macintoshplus** [comment]
I agree with you.

I rename the branch php-7.0 to php7-cli and I rename v1.3 to php7.

It's okay ?

**Comment by Jan-E** [comment]
Fine with me.

**Comment by alphp** [comment]
OK!

**Comment by macintoshplus** [comment]
Thanks for you help. I'm happy for the work finished on this extension.
I have realized the changes. 

Note: Please rebase your fork.
