### ISSUE TITLE
Change version 0.2.0-dev to 0.2.0.beta.1

### ISSUE THREAD

**Issue by alphp** [InExtenso/win32service#17]
Hi,

I suggest changing the version from 0.2.0-dev to 0.2.0.beta.1
Reasons:
1. The "dev" state is a state for continuously changing code.
2. There are no changes in the code, except corrections of errors.
3. There are no new features to implement.
4. It is necessary to test the current code, situation commonly associated with the "beta" phase.

That's why I propose the change to "beta".
The numbering 0.2.0.beta.1 can be modified consistently as needed (0.2.0.beta.2, for example)

**Comment by macintoshplus** [comment]
Done
