### ISSUE TITLE
archive-svn branch with history

### ISSUE THREAD

**Issue by alphp** [InExtenso/win32service#18]
Hi, I'm import the archived svn repository with history in
https://github.com/alphp/win32service/tree/archived-svn

**Comment by macintoshplus** [comment]
Good work.
You want add this branch into my repo ?

**Comment by alphp** [comment]
Yes, it is the right place.

**Comment by macintoshplus** [comment]
OK, How to ? You create a new PR or I must run your commands for import the SVN history ?

**Comment by alphp** [comment]
I think the simplest thing is to add my repository as a "remote", if you do not already have it.
This way you can create a new branch from any of mine.
That's the method I used to create the archived-svn branch from the local repository where I've cloned the svn.php.net trunk.
```
git remote -v
git remote add alphp https://github.com/alphp/win32service.git
git fetch alphp
```

**Comment by macintoshplus** [comment]
The history is now into my repo. Thanks for your help.
