### ISSUE TITLE
Build test for PHP-7.2 (alpha)

### ISSUE THREAD

**Issue by alphp** [InExtenso/win32service#22]
Hello, I have tried to build win32service for PHP-7.2 (alpha) and everything points to the extension being prepared for the next PHP branch.

I have created a branch for the tests and adjustments (compiled with VC15): [php7.2](https://github.com/alphp/win32service/tree/php7.2)

**Comment by macintoshplus** [comment]
Hi,
Me too in the [less_admin branch](https://github.com/InExtenso/win32service/tree/less_admin).

I have add the image param and VC version into the matrix for build all version of php 7.
But I have a problem for work fine.

See: https://ci.appveyor.com/project/macintoshplus/win32service/build/job/4j98a1vedrqpspet

**Comment by macintoshplus** [comment]
Yes, build successfully !
https://ci.appveyor.com/project/macintoshplus/win32service/build/job/vb2atbcfl54kmfnt/artifacts

**Comment by alphp** [comment]
I just added the necessary changes in the php7 branch to build the branches of php 7.0, 7.1 and master.

**Comment by macintoshplus** [comment]
ok, after when PHP 7.2 will be released, I want only add the 7.2 branch and keep the master.
The branch `less_admin` will be merged into `php7` after many tests. Can you help me ?

**Comment by alphp** [comment]
OK, I'll be testing with PHP-7.2 until branch 7.2 is created. Until then you can have PR #24 on hold.

**Comment by macintoshplus** [comment]
I have just change the appveyor configuration on branch less_admin for switch to the 7.2 branch.

**Comment by macintoshplus** [comment]
The build fail with this error for php 7.0 and 7.2:

```
Cache 'c:\build-cache' - Uploading (110,645,898 bytes)...100%Error uploading cache entry to the cache storage: The maximum cache size of 1,000 MB will be exceeded.
```

For PHP 7.2:

```
ERROR: The system cannot find the file specified.
c:\build-cache\deps-7.2-vc15-x86.7z
```

[Console log](https://ci.appveyor.com/project/macintoshplus/win32service/build/less_admin.96/job/2m0j65q6li6lp4o7#L92)

**Comment by alphp** [comment]
Yes, try to clean cache of appveyor

**Comment by macintoshplus** [comment]
Hi,
The cache is clean.

For the SDK error, I have open en issue here: https://github.com/OSTC/php-sdk-binary-tools/issues/15
The answer proposed can work ?

**Comment by alphp** [comment]
In PR #24 I updated build scripts for support 7.2

**Comment by macintoshplus** [comment]
I have add a comment but the support is for `master` branch. The `PHP-7.2` branch has been created.

**Comment by macintoshplus** [comment]
Hi,

How to update our scripts for build PHP 7.2 with the new recommendations ?

https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2

**Comment by alphp** [comment]
Looks like I have work ahead of me.
In a few days I have it ready.

**Comment by alphp** [comment]
Hi, I updated the build scripts and now works on 7.0, 7.1 and 7.2 branches.
All in PR #24.

**Comment by macintoshplus** [comment]
The PR is merged. Thanks for your help!
