### ISSUE TITLE
win32service for PHP 7.2

### ISSUE THREAD

**Issue by akathartos** [InExtenso/win32service#28]
Will there be PHP 7.2 version of DLL available?

**Comment by macintoshplus** [comment]
Hi,

You can download the latest version from less_admin branch.
It's available here : https://ci.appveyor.com/project/macintoshplus/win32service/build/less_admin.115/job/u30oquj5q2h8t1k1/artifacts

Can you report your tests for improve this version and release it quickly ?

Thanks in advance.

**Comment by akathartos** [comment]
Hi,

x64 TS VC15 seems to be working properly in our environment, thank you very much!

Br,
Samuli
