### ISSUE TITLE
Extension 'win32service' not present.

### ISSUE THREAD

**Issue by vjaykoogu** [InExtenso/win32service#29]
I've installed as it's given  in readme section, but while running 'php --ri win32service' im getting **Extension 'win32service' not present.** 

Please guide me whats im doing wrong.

### Below steps i've followed for installation.
a) downloaded the Extenstion & unzip.
b) copy pasted **dll** files into **php/ext** dir.
c) in php.ini pasted this line **extension = php_win32service-7.0-ts-vc14-x86.dll**

**Comment by macintoshplus** [comment]
Hi,
What is the version of PHP used ? 32/64 bits ? ZTS/NTZ ?

Have you set the extension directory into the php.ini file ?

Have you get the extensions from the [PECL website](https://pecl.php.net/package/win32service) or from the [latest AppVeyor artifacts](https://ci.appveyor.com/project/macintoshplus/win32service/build/less_admin.115) ?

**Comment by vjaykoogu** [comment]
Thanks for your reply @macintoshplus , My PHP version is 7.0. and i've tried both ZTS/NTZ
Yes i've set  in php.ini.

I've downloaded from PECL website.

**Comment by vjaykoogu** [comment]
also im getting this popup while starting the services. 
![image](https://user-images.githubusercontent.com/87112/34716434-ded56098-f555-11e7-8a1a-4e5b35f31edc.png)
