### ISSUE TITLE
issues in start service or create service

### ISSUE THREAD

**Issue by lovekobeme** [InExtenso/win32service#31]
there's some picture, you can see it , i did't change anything in service.php. i can't understand what about it , it's dramatic. win10 environment
![qq 20180528135506](https://user-images.githubusercontent.com/26919967/40599795-77f82574-6281-11e8-9e23-fe9330130539.png)
![qq 20180528135741](https://user-images.githubusercontent.com/26919967/40599796-78531722-6281-11e8-8a13-56470209d671.png)
![qq 20180528140218](https://user-images.githubusercontent.com/26919967/40599797-78aae902-6281-11e8-98ea-718be7272a50.png)
[service_20180528.log](https://github.com/InExtenso/win32service/files/2043902/service_20180528.log)

**Comment by macintoshplus** [comment]
Hi,

Thanks for the interest in this extension.

Can you describe your work environment ?

PHP version ?
PHP X64 or X86 ?
PHP NTS or TS ?

When you run the script for add the new service have you open the command line windows with administrator's privileges ?

**Comment by lovekobeme** [comment]
yeah, i have administrator's privileges. thanks for you Answer.
php7.0.29
PHP X86
PHP TS 
i create environment from wampserver3.1.3_x86.exe
1. i can't make service from other params, example : 'params' => '"' . __DIR__.'\c.php'. '" run',
![qq 20180529081842](https://user-images.githubusercontent.com/26919967/40632382-075103b6-6319-11e8-84a7-05c4e4a2c8d2.png)
2.when i create it and run it suceess, then, i do some steps testing something.
example : delete 1.txt>stop service> start service>service run success>but can't find 1.txt in my "D:\wamp\www\test" dir. 
i do these steps many times, but  can't touch 1.txt.(i did't change any code in service.php after when i run cmd "php service.php create start", because if i do that, then i can't run success the service, maybe service has strict regulations,they can find if i do something change then did't allow start the service)
![qq 20180529084015](https://user-images.githubusercontent.com/26919967/40632705-63150690-631c-11e8-9194-eec488f56c44.png)
![qq 20180529084240](https://user-images.githubusercontent.com/26919967/40632706-6369595c-631c-11e8-94d5-dc7129ae6099.png)
[service_20180529.log](https://github.com/InExtenso/win32service/files/2046409/service_20180529.log)

**Comment by macintoshplus** [comment]
Hi,

The goal of the `service.php` example is show how to manage the service in one object in one PHP File.

You can copy-it and customize this file for your tasks. For this, [copy it](https://github.com/InExtenso/win32service/blob/less_admin/examples/service.php) in you project and put you custom code in the [function `main_loop`](https://github.com/InExtenso/win32service/blob/less_admin/examples/service.php#L147).

Caution, the time of execution in `main_loop` function is limited to 30 seconds. This limit is set by windows service manager for ask  to the service her current state.

After writing the code, register the service with this command: `php service.php create` and start the service with the Windows Service Manager or this command: `netstat <service_name>`.

In you case, you want run another script in service. This script must execute the infinite loop like [this function](https://github.com/InExtenso/win32service/blob/less_admin/examples/service.php#L180).

**Comment by macintoshplus** [comment]
Look this example code: https://github.com/InExtenso/win32service/blob/less_admin/examples/sample.php
It is the minimum code for use this extension.

**Comment by lovekobeme** [comment]
Yeah, at example above, i'm copy 'win32service/examples/service.php' and customize it.
[service.zip](https://github.com/InExtenso/win32service/files/2047854/service.zip)
![qq20180529183814](https://user-images.githubusercontent.com/26919967/40654485-0db6990c-6371-11e8-8546-d53f4fe5ba6a.png)

**Comment by macintoshplus** [comment]
In your screenshot, the "params" is set to the file "c.php" this file is used for run the service.

The `c.php` file has the main loop for service and change the service state seem the `run()` function present in the `service.php` ?

Replace the `param` value by `'"'.__FILE__'" run'`. Remove the current service, re-create and start-it.

Edit: Please, paste you code into the comment ;-)

**Comment by lovekobeme** [comment]
yeah,i upload my code in previous comment(service.zip).
I have no main loop and I can't do it.
![qq 20180530111827](https://user-images.githubusercontent.com/26919967/40697213-cbe5508c-63fb-11e8-89b3-1fb1a92ba96a.png)
I want to build one service excute php script instead of Command Line Interface excute php script.
It's could excute the php script when i start the service.(example: touch 1.txt or do something).
It's could i do it?

2.when i create it and run it suceess, then, i do some steps testing something.(Replace the param value by '"'.__FILE__'" run')
example : create service>start service>delete 1.txt>stop service> start service>service run success>but can't find 1.txt in my "D:\wamp\www\test" dir. (For this, i want to excute the php script when i start the service.(example: touch 1.txt))
i do these steps many times, but  can't touch 1.txt.(i did't change any code in service.php after when i run cmd "php service.php create start", because if i do that, then i can't run success the service, maybe service has strict regulations,they can find if i do something change then did't allow start the service)
![qq 20180529084015](https://user-images.githubusercontent.com/26919967/40632705-63150690-631c-11e8-9194-eec488f56c44.png)
![qq 20180529084240](https://user-images.githubusercontent.com/26919967/40632706-6369595c-631c-11e8-94d5-dc7129ae6099.png)

**Comment by macintoshplus** [comment]
I have written another example based on `service.php` file:
[examples.zip](https://github.com/InExtenso/win32service/files/2053968/examples.zip)

I have move the technical code into the abstract class `AbstractWinServiceManager` for more clearity.

Read the `service.php` file and custom it if you want. But caution to the `$service['service']['service']` value. This is the Windows Service Manager identity. It'is used for manage and run the service. Must don't change between management and execution workspace.

![image](https://user-images.githubusercontent.com/814683/40721984-5bd44350-641b-11e8-8246-5b6ea9a41e5f.png)

Hopefully it can help you.
