### ISSUE TITLE
Drop support for PHP 7.0

### ISSUE THREAD

**Issue by macintoshplus** [InExtenso/win32service#37]
The branch 7.0 of PHP is the end of life. Can I drop the extension support for this version?

**Comment by macintoshplus** [comment]
Now, the build for PHP 7.0 on AppVeyor does not work.
I need to disable it for continue the build.

**Comment by ghost** [comment]
I think you can drop php 7.0 extension support without problems :)

**Comment by xingguo18** [comment]
I think that no problems.

**Comment by alphp** [comment]
Maybe also drop the support for PHP-7.1?
In 5 months, 7.1 will reach the EOL and will no longer have security support.
https://php.net/supported-versions.php

**Comment by macintoshplus** [comment]
I have written a blog post for this https://nahan.fr/win32service-php-7-0-and-7-1-support/
