### ISSUE TITLE
Support for adding Dependencies

### ISSUE THREAD

**Issue by faithfulman18** [InExtenso/win32service#40]
It would be most helpful to add support for dependencies.  For example, if you are building a service that relies on a mysql database, or any other service to be up and running before it makes sense for your service to start.

Is this a possibility?

**Comment by macintoshplus** [comment]
@faithfulman18  Can you test the version available here:
https://ci.appveyor.com/project/macintoshplus/win32service/builds/22402549

**Comment by faithfulman18** [comment]
I've gone to that page, however, I don't see any dll file to download?  Just a list of jobs that bring up a console when you go to one of them.

?

**Comment by macintoshplus** [comment]
Yes, click on the configuration needed (x86/x64, PHP7.1/7.2/7.3) and click on "artifacts" for download zip who contains the DLL (NTS or ZTS).

Now you can download the pre-builded DLL here: https://github.com/win32service/win32service/releases/tag/v0.4.0
or here: http://pecl.php.net/package/win32service/0.4.0/windows
