### ISSUE TITLE
Wait for the connection timeout (60,000 milliseconds) for the PHP service for tests service.

### ISSUE THREAD

**Issue by leihenshang** [InExtenso/win32service#43]
PS D:\webTestProject\php_win32service\examples> php .\managementActions.php start my_test_service
Service : localhost\my_test_service
Error : (1053) Win32Service\Exception\ServiceStateActionException: Unable to start service
PS D:\webTestProject\php_win32service\examples>

windows Event viewer:
Wait for the connection timeout (60,000 milliseconds) for the PHP service for tests service.
I used administrator to open the installation but could not start.

**Comment by leihenshang** [comment]
windows 10 64bit home basic

**Comment by macintoshplus** [comment]
Thanks for the feedback.

By default, all management action need the administrator right.
Can you show the code into `managementActions.php` ?
And the configuration of the `my_test_service` service ?

If you start the service by the windows service manager, the service start ?

**Comment by leihenshang** [comment]
Thank you very much!I'm done.Use the latest example.
