### ISSUE TITLE
PHP 7.4 Support

### ISSUE THREAD

**Issue by macintoshplus** [InExtenso/win32service#44]
Build this extension for PHP 7.4.

Actualy the extention cannot be loaded by the PHP 7.4alpha1 build with this warning:

```Warning: PHP Startup: Can't load module 'ext\php_win32service.dll' as it's linked with 14.21, but the core is linked with 14.20 in Unknown on line 0```

I have open a thread on the IIS forum:
https://forums.iis.net/p/1242842/2149922.aspx?p=True&t=636967270928023329

**Comment by alphp** [comment]
In https://github.com/php/php-src/blob/PHP-7.4.0alpha1/.appveyor.yml
```
image: Visual Studio 2017
PHP_BUILD_CRT: vc15
```
In https://github.com/win32service/win32service/blob/v0.4.x/appveyor.yml
```
- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PHP_REL: 7.4
      ZTS_STATES: enable disable
      PHP_BUILD_CRT: vs16
```

**Comment by alphp** [comment]
I have already seen that PHP-7.4 is compiled with vs16, I reverse my commit.

**Comment by alphp** [comment]
https://www.apachelounge.com/viewtopic.php?p=38274
> It is only  a PHP start up  check and is new in PHP 7.4; it has been introduced to ensure that only modules which have been built with a linker version less than or equal to the linker version which has been used to built the core can beloaded, just to prevent eventual issues wrt. dynamic loading.  The coming 7.4.0alpha2 should be build at least with 14.21.

**Comment by alphp** [comment]
https://github.com/php/php-src/pull/4294

**Comment by cmb69** [comment]
> The coming 7.4.0alpha2 should be build at least with 14.21.

Yes. The recent [snapshots](https://windows.php.net/downloads/snaps/php-7.4/) are already build with 14.21.

**Comment by macintoshplus** [comment]
Thank you very much. It works fine with the latest snapshot.
