### ISSUE TITLE
crashes phpinfo( INFO_MODULES ) 

### ISSUE THREAD

**Issue by ASchmidt1** [InExtenso/win32service#45]
Version 0.4.0 (Feb 2019) will crash phpinfo() under PHP 7.3 and 7.2

Can be circumvented by unselecting INFO_MODULES, or by disabling the win32service extension.

Anything greater 7.3.6 oder 7.2.19 is affected.

**Comment by alphp** [comment]
I checked both the February release
https://github.com/win32service/win32service/releases/tag/v0.4.0
as the last build with PHP-7.3.6-TS-x64.
I also tried the official binary downloaded from https://windows.php.net/downloads/pecl/releases/win32service/
None of the binaries has given problems.
Can you give more information about your environment?

**Comment by ASchmidt1** [comment]
I accidentally stumbled across that as I was working on an OPcache bug, which required me to test development builds and release candidates. Despite OPcache, Wincache, and xDebug disabled, phpinfo(8) will fail. But, it will work if all extensions are active, EXCEPT win32service.

I'm using the 2019-02-20 build:
https://pecl.php.net/package/win32service/0.4.0/windows
which works fine with previous 7.3 and 7.2 versions.

But it DOES fail with the 7.3.7-RC3:
https://windows.php.net/qa/#php-7.3
per example, and had as well with a development build of 7.2.21-dev.

PS - to be clear, my PHP service that uses your extension continues to function just fine in each case. The problem is ONLY the phpinfo(8).

**Comment by alphp** [comment]
With PHP-7.3.7RC3-TS-x64 crash wen phpinfo () is invoked.
Attached test script.
[win32service-crash.zip](https://github.com/win32service/win32service/files/3327020/win32service-crash.zip)

**Comment by macintoshplus** [comment]
Hi,

Thanks for your feedback. To search the solution, can you send me the PHP output when it crashes ?

**Comment by ASchmidt1** [comment]
I forgot to mention before - running phpinfo() from the php-cli command line does NOT cause problems. It only crashes when running FCGI (php-cgi). 

First I fixed the test script, so that the php.exe and php.ini could be located in the "Program Files" folder (embedded space in path):
```
<?php
	$php = PHP_BINARY;
	$ini = '"'.php_ini_loaded_file().'"';
	$iniopt = $ini ? "-c $ini" : '';
	$iniopt .= extension_loaded('win32service') ? '' : ' -d extension=php_win32service.dll';
	$command = "\"$php\" $iniopt -r \"phpinfo();\"";
	exec($command, $output, $status);
	var_dump($output, $status);
```
Then I ran your script on the command line - result is file "clioutput.txt".
[clioutput.txt](https://github.com/win32service/win32service/files/3327098/clioutput.txt)

No idea what your test script is attempting, but just in case here "phpinfo.cli.txt", which is the command line output of phpinfo().
[phpinfo.cli.txt](https://github.com/win32service/win32service/files/3327110/phpinfo.cli.txt)

However HERE are the RELEVANT files that are the CAUSE of the php-cgi crash. I ran phpinfo() using php-cgi.exe, first with win32service ACTIVE, and then with win32service removed. Please note the garbled HTTP header when win32service is ACTIVE:


[phpinfo.cgi.html.txt](https://github.com/win32service/win32service/files/3327142/phpinfo.cgi.html.txt)
[phpinfo.disabled.cgi.html.txt](https://github.com/win32service/win32service/files/3327143/phpinfo.disabled.cgi.html.txt)
[phpinfo.cgi.html.zip](https://github.com/win32service/win32service/files/3327145/phpinfo.cgi.html.zip)

**Comment by ASchmidt1** [comment]
> Hi,
> Thanks for your feedback. To search the solution, can you send me the PHP output when it crashes ?

Here the side by side of the php-cgi.exe output. Notice the garbled "Content-Type" header in line 2 when win32service extension is loaded.
![inactive-vs-loaded](https://user-images.githubusercontent.com/12052792/60131187-c7706100-9766-11e9-81d4-39e8d4af9eb6.png)

**Comment by macintoshplus** [comment]
Result of my test in command line:

PHP version | Result for TS | result for NTS
------------ | ------------- | -------------
PHP 7.2.20RC3 | :heavy_check_mark:  | :heavy_check_mark: 
PHP 7.3.7RC3 | :heavy_check_mark:  | :heavy_check_mark: 

Result with IIS:

PHP x64 version | Result for TS | result for NTS
------------ | ------------- | -------------
PHP 7.3.6 | :no_entry_sign:   | :heavy_check_mark: 
PHP 7.3.7RC3 | :no_entry_sign:   | :heavy_multiplication_x:  
PHP 7.2.20RC3 | :no_entry_sign:   | :heavy_multiplication_x:  
PHP 7.2 snapshot | :no_entry_sign:   | :heavy_multiplication_x:

**Comment by macintoshplus** [comment]
Ok, what is your web server ? IIS ? Apache ?

The PHP build is: TS or NTS ?

**Comment by ASchmidt1** [comment]
Hi, IIS, NTS. However, I'm now able to produce the problem without using IIS. Opening a command window, I can use:
php-cgi -i >output.txt
and it will produce an INTACT content-header, even if win32service is active.

However, running:
php-cgi phpinfo.php >output2.txt 
[phpinfo.php.txt](https://github.com/win32service/win32service/files/3327233/phpinfo.php.txt)
will produce the garbled content-header.

So this completely rules out IIS or similar environmental factors. This is now plain-vanilla php-cgi.exe.

**Comment by macintoshplus** [comment]
Hi,

Can you try with [this build](https://ci.appveyor.com/api/buildjobs/nikudwy9eoa3hfi2/artifacts/php_win32service-0.4.0-v0.4.x-aa6d478e-7.3.zip) and send me the phpinfo html page ?

**Comment by ASchmidt1** [comment]
[fixed.html.txt](https://github.com/win32service/win32service/files/3328383/fixed.html.txt)
Looks okay now: correct Content-Type header if running php-cgi in command line, and also if running from IIS.

**Comment by macintoshplus** [comment]
okay, the problem come from the PHP version check. This check is necessary only for PHP 7.0.0 and 7.1.0.
I remove it.

The problem is only from the RC version or the snapshot.

**Comment by macintoshplus** [comment]
Preview: 
![image](https://user-images.githubusercontent.com/814683/60212843-7b0a4b80-9862-11e9-9ad6-e5155317c7f7.png)


![image](https://user-images.githubusercontent.com/814683/60212807-67f77b80-9862-11e9-90c0-7b171dfe0553.png)


You can download the version 0.4.1 from the [artifact of AppVeyor](https://ci.appveyor.com/project/macintoshplus/win32service/builds/25568314) at the end of build.

**Comment by ASchmidt1** [comment]
Thanks, 0.4.1 downloaded, rebooted, and PHP 7.3.7 phpinfo() working under IIS.
