### ISSUE TITLE
Add unsupported version into the README

### ISSUE THREAD

**Issue by macintoshplus** [InExtenso/win32service#47]
Add a note into the README file about the incompatibility with PHP 7.0.0 and 7.1.0.

**Comment by alphp** [comment]
Maybe delete 7.1 from the build matrix in appveyor.yml?
In 5 months 7.1 will arrive at the EOL and will stop having security support.
https://php.net/supported-versions.php

**Comment by macintoshplus** [comment]
Yes after the EOL 😉

**Comment by macintoshplus** [comment]
The goal of this issue is not understandable ? I misspoke maybe.

I want only move the message displayed in Win32Service informations for the PHP version 7.0.0 and 7.1.0 into the README.

After the EOL of the PHP 7.1, we can delete all messages into README and web site. Excepted the PHP official documentation.
