### ISSUE TITLE
Can I build it on Linux ?

### ISSUE THREAD

**Issue by borgogelli** [InExtenso/win32service#48]
I would to install the win32service extension on a Linux server to run a static analysis on my source code which will be then deployes to a Windows system.
Could I build that extension on Linux ?
The phpize command returns an error "Cannot find config.m4".

**Comment by macintoshplus** [comment]
Hi,

Thanks for your interest for this extension.

I have a bad news for you, this extension work only on Windows Operating System.

For run your PHP script as service on Linux, you can use Supervisord, or Systemd or another service available for run a script in background.

Or simply with this way: `php myscript.php &`

**Comment by alphp** [comment]
The only sense that this extension would have in Linux would be to control a service of a Windows computer from a Linux computer.

For that situation you can try PowerShell for Linux.
