### ISSUE TITLE
Characters encoding problems

### ISSUE THREAD

**Issue by ghost** [InExtenso/win32service#51]
Hi,

I've got a problem with characters encodings when displayed in Windows service description :
![image](https://user-images.githubusercontent.com/46027501/70243891-ca3e9b80-1773-11ea-9f25-5deb5b961d2e.png)
Here "é" characters is replaceed with bad ones...

My PHP file is correctly encoded in UTF8.

**Comment by macintoshplus** [comment]
Hi,

Windows does not use UTF-8 to encode data. To display service information correctly, you must convert the information encoding to the Windows encoding.
Use mbstring to convert all string from UTF-8 to Windows-1252.

PHP Multi-Byte supported encoding : https://www.php.net/manual/en/mbstring.supported-encodings.php
PHP function to conver encoding : https://www.php.net/manual/en/function.mb-convert-encoding.php

**Comment by ghost** [comment]
Thank you very much for explanation @macintoshplus !
