### ISSUE TITLE
0.4.2 required for 7.4 - but labeled as "not for production"

### ISSUE THREAD

**Issue by ASchmidt1** [InExtenso/win32service#53]
With the public release of PHP 7.4 having been backleveled to the previous VC version, the win32service "release" 0.4.1 is NOT compatible with PHP 7.4. 

PHP will fail to start with message
"PHP Warning:  PHP Startup: Unable to load dynamic library 'win32service' (tried: C:\Program Files\PHP\v7.4\ext\php_win32service.dll (The specified procedure could not be found.)

Your development version 0.4.2 is compatible and will work with the PHP 7.4 public release - but the project page instructs to "not use for production".

**Comment by alphp** [comment]
In PECL page you can download official 0.4.1 release that is compatible with PHP-7.4 https://pecl.php.net/package/win32service

**Comment by ASchmidt1** [comment]
Uh sorry - that was confusing:
The PECL site very clearly states the OLD date of 2019-07-09 for 0.4.1,, but once you download and inspect the inside of the ZIP file, you indeed find a much newer DLL, dated 2019-12-05.

I can confirm that the 0.4.1-build-2019-12-05 does indeed work with the public release of PHP 7.4
