### ISSUE TITLE
Usage of win32_set_service_exit_code and win32_set_service_exit_mode

### ISSUE THREAD

**Issue by ASchmidt1** [InExtenso/win32service#54]
I have the following PHP code in my service:
```
win32_set_service_exit_code( 1 );       // Only used for non-graceful shutdown.
win32_set_service_exit_mode( false );  // Graceful = FALSE; should trigger service recovery.
```
I expected the service to shutdown "harshly", causing Windows to follow the service's recovery settings.

Instead, the service created Application Event Log entries:
```
Application Event Log: Event ID 7024 
    The ... service terminated with the following service-specific error: 
    Incorrect function.
    <EventData>
		<Data Name="param1">(the name of my service)</Data>
		<Data Name="param2">%%1</Data>
		<Binary>41006E006D004D0065006400690061000000</Binary> ("AnmMedia" = the short name of my service) 
    </EventData>
```

Note the %%1 as param2.

**Comment by macintoshplus** [comment]
The Windows Service Manager use the recovery parameter (if set correctly) when the service exited abnormally.

But at the same time, the Windows behavior when a service fail is always registering an event in the log.

What is the problem with the extension?

**Comment by ASchmidt1** [comment]
Merci Jean-Baptiste for your response.

It's very possible that I'm not correctly using your extension.

I have been successfully using the Windows service recovery options with various other services for many years. However, with my own PHP-written service, I have yet to be able to ever trigger a service recovery (after first two failures).

I was only reporting the Event Log entry, in case the information was relevant.

My first attempt had been:
`exit( -1 );                     // Exit with error code, in hopes it triggers service recovery.`

When that didn't work, I replaced it with:
```
win32_set_service_exit_code( 1 );			// Only used for non-graceful shutdown.
win32_set_service_exit_mode( false );		// Graceful = FALSE; should trigger service recovery.
```
which now also didn't work.

But... after some more research I'm wondering if the problem is, that I _am_ setting an "exit code" at all, rather than just letting it default to 0? Maybe it would be sufficient to _only_ use the **mode**:
`win32_set_service_exit_mode( false ); `
as long as "Enable actions for stops with errors" (sc failureflag) is _not_ turned on.

And, if someone **sets a non-zero "exit code**" in PHP, then one _must_ turn **on** "Enable actions for stops with errors" (sc failureflag) in the  recovery options?

**Comment by ASchmidt1** [comment]
PS: I mentioned the 7024 event log - because that is NOT how other Windows services behave. When one of my regular services "crashes" occasionally, I will instead see event log entries like:

7031 - The ... service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in ... milliseconds: Restart the service.

or 

7034 - The ... service terminated unexpectedly.  It has done this 3 time(s).

**Comment by macintoshplus** [comment]
OK, I have more information.

When you want automatically restart a service with this extension, you need
1) enable the recovery action in windows service configuration
2) call win32_set_service_exit_code(1) and win32_set_service_exit_mode(false) on starting to pre-config the output mode.
3) On crash the configuration will be used to send a signal to Windows Service Manager.
4) On normally exit, you need call win32_set_service_exit_mode(true) before the exit.

For info, the Win32Service documentation: https://www.php.net/manual/en/book.win32service.php

I have written a library to help use this extension. It's here: https://github.com/win32service/service-library

Please consider using it.

In the Library code, you have this method: 
https://github.com/win32service/service-library/blob/aae366caf7c8f2b1d96e2d9d31a073c1992d849c/lib/Model/AbstractServiceRunner.php#L218

**Comment by macintoshplus** [comment]
Hi @ASchmidt1,

Have you solved our issue?

**Comment by ASchmidt1** [comment]
Dear Jean-Baptiste - thank you very much for your follow up.

Based on the additional information and my new understanding (of the exit status, vs. the additional exit RC code, and how those two are targeted by the recovery settings), I had made changes to my code AND my recovery settings.

Fortunately, my service is very stable overall and ideally would never "crash", so it might run for quite a while before I get to validate my code changes again and report back here. (Also, I'm in the middle of another project, so I can't divert time to artificially forcing the scenario for a few weeks.)

**Comment by macintoshplus** [comment]
Dear Andy, thank you for your answer. I close this issue, you can reopen if you need or open a new issue for another problem.
