### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by sambenne** [InExtenso/win32service#62]
Hi, I am getting access denied no matter the method used.

## The PHP

```
PHP Version => 8.0.8

System => Windows NT DESKTOP-QE919S8 10.0 build 19042 (Windows 10) AMD64
Build Date => Jun 29 2021 16:00:22
Build System => Microsoft Windows Server 2019 Datacenter [10.0.17763]
Compiler => Visual C++ 2019
Architecture => x64
```

## The extension

```
Win32 Service support => enabled
Version => 1.0.0
Current SAPI => cli

Function => State for the current SAPI
win32_start_service_ctrl_dispatcher => enabled
win32_set_service_status => enabled
win32_get_last_control_message => enabled
win32_set_service_exit_mode => enabled
win32_set_service_exit_code => enabled
win32_create_service => enabled
win32_delete_service => enabled
win32_query_service_status => enabled
win32_start_service => enabled
win32_stop_service => enabled
win32_pause_service => enabled
win32_continue_service => enabled
win32_send_custom_control => enabled
```

What do I need to do to get access. There does not seem to be any information about fixing this.

**Comment by macintoshplus** [comment]
Hi, thank you for this feedback.

Can you explain how you run the PHP script step by step? And share your script if possible?

**Comment by macintoshplus** [comment]
@sambenne any informations?

**Comment by sambenne** [comment]
Sorry, Github was not sending me notifications.

I am currently doing ```LdapRecord\Models\ActiveDirectory\User::get()``` and this returns all the users as I want. This tells me that the credentials are correct and I can talk to the LDAP server.

However, when trying to login using Laravel it always seems to fail. I am upgrading from adldap2/adldap2-laravel and I have followed the instructions but I can't seem to see why it fails.

**Comment by macintoshplus** [comment]
Hi, 

I don't understand the link with the PHP Extension Win32Service and the issue explained in first comment...

**Comment by macintoshplus** [comment]
I close this issue. Open a new issue if help needed.
