### ISSUE TITLE
Can't use in embed sapi

### ISSUE THREAD

**Issue by EionRobb** [InExtenso/win32service#63]
I'm using the "embed" sapi, from the php_embed.c code that comes with PHP, embedded using embeder2 (https://github.com/RDashINC/embeder2), however win32service rejects anything that isn't the "cli" sapi.  I recompiled win32service without the check for "cli" and it runs with the embeder2 exe fine.

Is it possible to remove the "cli" check altogether?

**Comment by macintoshplus** [comment]
Hi,

Thanks you for your feedback. Unfortunately, I cannot remove the security check on functions available only on cli SAPI.

When you use on embedded, you can apply a patch to add the embed sapi into the security check.

I can accept a pull request to add the embedded sapi in security check.

**Comment by EionRobb** [comment]
Fair enough, couldn't hurt to ask :)

I did end up patching and rebuilding win32service to look for "embed" instead, but I'll change that over to look for "cli" too and try and wrangle that into a PR :)

**Comment by macintoshplus** [comment]
Thanks for your merge request https://github.com/win32service/win32service/pull/64.
