### ISSUE TITLE
Interact with Win32Services in a browser: ServiceAccessDeniedException

### ISSUE THREAD

**Issue by fghber** [InExtenso/win32service#67]
I would like to allow users of my intranet set to start/stop a Windows service. It sounds like the Win32Service extension for PHP and this library would make this feasible. When I invoke the process with my own/an admin account it works, but when a regular user browses to the sight I get an exception:

`Service : localhost\my_test_service Error : (5) Win32Service\Exception\ServiceAccessDeniedException: Access to service my_test_service is denied`

The scripts allow me to interact with the service when used on the command line but no in the browser.
Is this scenario not supported, or do I have to add a specific user as described here https://win32service.mactronique.fr/service_library.html with `sdset`?

**Comment by fghber** [comment]
Hi,
thank you for your response and for moving it to the right place.
I am using ISS (10) but cannot configure it as needed.

I think I know the general steps:
1. Assign a user identity to the IIS AppPool that runs the PHP process in question.
2. Grant the user identity that runs the AppPool in question the rights to start/stop a service, e.g. using the `sdset` as shown on the wiki or `subinacl /service my_test_service /GRANT=YOURDOMAIN\srv_user=TOP`
3. Restart everything.

This should be it, I think, but it is not working. What could be missing?

**Comment by macintoshplus** [comment]
This page can be useful http://woshub.com/set-permissions-on-windows-service/

**Comment by macintoshplus** [comment]
@fghber I close this issue. Open an new issue if your need help.
