### ISSUE TITLE
Missing win32 binaries on Github releases page

### ISSUE THREAD

**Issue by evandrocoan** [InExtenso/win32service#68]
They are available on https://pecl.php.net/package/win32service/0.4.2/windows
![image](https://user-images.githubusercontent.com/5332158/152414124-1b9d17bd-5658-48fe-86e8-b8a5c1815f79.png)

But on Github they are not available:
![image](https://user-images.githubusercontent.com/5332158/152414169-001f3bc2-8b52-40dd-9210-e071009c54a3.png)

When I first saw it on Github, I thought the project did not supported x86, then, I went to into building it from source, only to find out later that the x86 binaries were available all along.

**Comment by macintoshplus** [comment]
Hi, thank you for your report. I know this issue [AppVeyor x86 build fail](https://github.com/win32service/win32service/issues/65).

Why do you need an x86 version of this extension?

I'm happy if you have any information to help me to solve this issue. Or if you know another service to build the extension.

**Comment by evandrocoan** [comment]
The x86 would be for a legacy project being updated with PHP 7.4.  I just downloaded it from https://pecl.php.net/package/win32service/0.4.2/windows which has the x86 binaries.

**Comment by macintoshplus** [comment]
Good news. I close this issue :+1:
