### ISSUE TITLE
New release supporting php 8.2

### ISSUE THREAD

**Issue by evandrocoan** [InExtenso/win32service#72]
Hi. I just downloaded [php_win32service-8.1-nts-vs16-x86.dll](https://github.com/win32service/win32service/releases/download/v1.0.2/php_win32service-8.1-nts-vs16-x86.dll) from https://github.com/win32service/win32service/releases and put it into php 8.2, but looks like the extension was not loaded:
```
PHP Fatal error:  Uncaught Error: Call to undefined function win32_query_service_status()
```

Does it need a new binary release to support php 8.2? I see the master branch has this commit: https://github.com/win32service/win32service/commit/527c27dc3a0f19e9f2be7c5321b411f613094337 try PHP 8.2 build

Edit: I just found these errors on php start up:
```
PHP Warning:  PHP Startup: win32service: Unable to initialize module
Module compiled with module API=20210902
PHP    compiled with module API=20220829
These options need to match
 in Unknown on line 0
```

**Comment by macintoshplus** [comment]
Hi,

Thank you for opening this issue. To use the PHP extension Win32Service, you must download the extension build for the used PHP version.

To download the PHP 8.2 version of Win32Service, go on this page [https://nahan.fr/download/win32Service-1-0-2-for-PHP-8-2-dev](https://nahan.fr/download/win32Service-1-0-2-for-PHP-8-2-dev)

If you have any error or problem with the PHP 8.2 version of Win32Service, please open a new issue.

**Comment by evandrocoan** [comment]
Thanks for the fast response. I will be using it.
