### ISSUE TITLE
Strange behavior on "pause"

### ISSUE THREAD

**Issue by stef-pellegrino** [InExtenso/win32service#74]
With PHP 7.1 , 64 bit windows 11

`win32_pause_service(SERVICE_NAME);`

seems ok, but...

I  noticed in the services.msc that my service remains "running" !??

In the running loop, the `win32_get_last_control_message()` always returns` WIN32_SERVICE_START_PENDING`

**Comment by macintoshplus** [comment]
Hi @stef-pellegrino,

Thanks for your feedback. I am investigating this issue.

**Comment by macintoshplus** [comment]
Hi @stef-pellegrino,

Why you cannot upgrade your project to the PHP 8.1+ version?

PHP 7.1 and the win32service 0.4 are not maintained anymore.


After receiving a control message, you must call the `win32_set_service_status` [1] with the new service state to update the status in SMC. But on Windows 11 this call seems to change.

[1] https://www.php.net/manual/en/function.win32-set-service-status.php

**Comment by macintoshplus** [comment]
I close this issue because no response. If you have always this behavior, reopen the issue.
