### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by arjanbosboom** [InExtenso/win32service#75]
I'm now using a win32service dll from:
https://github.com/evandroforks/php-win32service/releases/tag/v1.0.2-php82

Can you please make a official build for PHP 8.2 ?

**Comment by macintoshplus** [comment]
The official DLLs are on my WebSite 

https://nahan.fr/download/win32Service-1-0-2-for-PHP-8-2-dev

Unfortunately, I do not have any feedback to fix issues. I started the PHP 8.3 compatibility check, the next version will be an automatic build for PHP 8.2.

**Comment by macintoshplus** [comment]
The build for PHP 8.3 is available here: https://nahan.fr/download/win32service-1-0-2-for-php-8-3
