### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by NeilWhitworth** [InExtenso/win32service#78]
I have been trying to update one of our applications from PHP 7.4 to PHP 8.3. I have tried the versions from https://github.com/win32service/win32service/issues/75 

* The extension will load, and shows in php -m
* using the symfony bundle I can register & unregister service(s)

however I cannot get the service to start & run.

Windows event viewer shows:-
`A timeout was reached (300000 milliseconds) while waiting for the Test Service service to connect.`

The log file shows:-

`
[2024-03-07T11:07:21.038914+00:00] console.CRITICAL: Error thrown while running command "win32service:run TestService 0". Message: "Error on start service controller" {"exception":"[object] (Win32Service\\Exception\\Win32ServiceException(code: 0): Error on start service controller at C:\\Src\\BitBucket\\TestService\\vendor\\win32service\\service-library\\lib\\Model\\AbstractServiceRunner.php:116)","command":"win32service:run TestService 0","message":"Error on start service controller"} {"threadNumber":0}
`

OS Name:	Microsoft Windows 10 Enterprise
Version:	10.0.19045 Build 19045

`php -v
PHP 8.3.2 (cli) (built: Jan 16 2024 20:48:07) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.3.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.2, Copyright (c), by Zend Technologies
`

```
php -i

win32service

The maintainer needs your feedback (good or bad), please send it to: win32service@mactronique.fr
Please report your bugs with this extension here : https://bugs.php.net/
Home page: http://win32service.mactronique.fr/
Library for help you to use this extension: https://github.com/win32service/service-library and https://github.com/win32service/Win32ServiceBundle for Symfony

Win32 Service support => enabled
Version => 1.0.2
Current SAPI => cli

Function => State for the current SAPI
win32_start_service_ctrl_dispatcher => enabled
win32_set_service_status => enabled
win32_get_last_control_message => enabled
win32_set_service_exit_mode => enabled
win32_set_service_exit_code => enabled
win32_create_service => enabled
win32_delete_service => enabled
win32_query_service_status => enabled
win32_start_service => enabled
win32_stop_service => enabled
win32_pause_service => enabled
win32_continue_service => enabled
win32_send_custom_control => enabled
```

**Comment by macintoshplus** [comment]
Thank you for this feedback. I read the problem.

**Comment by macintoshplus** [comment]
I just ran the test service on Windows 10 Pro (`Microsoft Windows [version 10.0.19045.3930]`) with PHP 8.3.2 NTS without problems.

I ran the service-library 1.0.1 sample service without any errors.

```
php.exe -v
PHP 8.3.2 (cli) (built: Jan 16 2024 20:48:07) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.3.2, Copyright (c) Zend Technologies
```

```
php.exe --ri win32service

win32service

The maintainer needs your feedback (good or bad), please send it to: win32service@mactronique.fr
Please report your bugs with this extension here : https://bugs.php.net/
Home page: http://win32service.mactronique.fr/
Library for help you to use this extension: https://github.com/win32service/service-library and https://github.com/win32service/Win32ServiceBundle for Symfony

Win32 Service support => enabled
Version => 1.0.2
Current SAPI => cli

Function => State for the current SAPI
win32_start_service_ctrl_dispatcher => enabled
win32_set_service_status => enabled
win32_get_last_control_message => enabled
win32_set_service_exit_mode => enabled
win32_set_service_exit_code => enabled
win32_create_service => enabled
win32_delete_service => enabled
win32_query_service_status => enabled
win32_start_service => enabled
win32_stop_service => enabled
win32_pause_service => enabled
win32_continue_service => enabled
win32_send_custom_control => enabled
```

**Comment by macintoshplus** [comment]
What is the user account used to run the service?

**Comment by NeilWhitworth** [comment]
I have now managed to get the service to start. It was due to the service environment not being as expected, and no _PHP_INI_SCAN_DIR_  variable being set. Due to the way php is deployed to our systems we required additional .ini files to be loaded to enabled extensions such as this one.

I have successfully started the service as both _Local System_  and as a named service account.

**Comment by macintoshplus** [comment]
Good news. I'm happy that you have solved your issue.
