### ISSUE TITLE
Add feature to manage service environment variable

### ISSUE THREAD

**Issue by jbcr** [InExtenso/win32service#80]
Specific environment variable for a service can be defined via the Windows Registry.

https://serverfault.com/questions/813506/setting-environment-variable-for-service

Add function to add, get, remove varriable for a specific service.

https://learn.microsoft.com/en-us/archive/msdn-magazine/2017/may/c-use-modern-c-to-access-the-windows-registry#reading-multi-string-values-from-the-registry

Create
https://learn.microsoft.com/fr-fr/windows/win32/api/winreg/nf-winreg-regcreatekeyexa

Get Value
https://learn.microsoft.com/fr-fr/windows/win32/api/winreg/nf-winreg-reggetvaluea

Set Key
https://learn.microsoft.com/fr-fr/windows/win32/api/winreg/nf-winreg-regsetvalueexa

Key: `HKLM\SYSTEM\CurrentSControlSet\Services\<service_id>\Environment`

Value: 
```
VAR1=value1
VAR2=val2
```
Type: `REG_MULTI_DZ`

Example:

https://aljensencprogramming.wordpress.com/tag/regopenkeyex/

Tools:

https://learn.microsoft.com/fr-fr/sysinternals/downloads/process-explorer

**Comment by macintoshplus** [comment]
added in 1.1.0-beta1
